---
- name: Deploy Nodejs App
  hosts: web
  tasks:

  - name: Make sure webapp dir exists
    file:
      path: /var/www/app/
      state: directory
      mode: '0755'

  - name: Ensure git is installed
    ansible.builtin.yum:
      name: git
      state: latest

  - name: Clone the repository
    ansible.builtin.git:
      dest: /var/tmp/gitrepo
      repo: "{{ git_repository }}"
      version: "{{ git_version }}"

  - name: copy node app to webapp directory
    copy:
      remote_src: true
      src: /var/tmp/gitrepo/rhel/webdev/hello.js
      dest: /var/www/app/hello.js

  - name: remove the git repository
    file:
      path: /var/tmp/gitrepo
      state: absent

#  - name: copy node app to webapp directory
#    copy:
#      src: hello.js
#      dest: /var/www/app/hello.js

  - name: restart nodejs
    systemd:
      name: node
      state: restarted
