---
- name: Deploy Nodejs App
  hosts: web
  tasks:

  - name: Make sure webapp dir exists
    file:
      path: /var/www/app/
      state: directory
      mode: '0755'

# TODO: get the file from a git repo

  - name: copy node app to webapp directory
    copy:
      src: hello.js
      dest: /var/www/app/hello.js

  - name: restart nodejs
    systemd:
      name: node
      state: restarted
